apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: organization-catalogue
  name: organization-catalogue
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: organization-catalogue
    spec:
      containers:
      - env:
        - name: PUBAPI_MONGO_USERNAME
          value: {{ required "Missing value PUBAPI_MONGO_USERNAME" .Values.PUBAPI_MONGO_USERNAME }}
        - name: PUBAPI_MONGO_PASSWORD
          value: {{ required "Missing value PUBAPI_MONGO_PASSWORD" .Values.PUBAPI_MONGO_PASSWORD }}
        - name: ENHETSREGISTERET_PROXY_URL
          value: {{ .Values.ENHETSREGISTERET_PROXY_URL }}
        name: organization-catalogue
        image: {{ required "Missing value ORGANIZATION_CATALOGUE_IMAGE" .Values.ORGANIZATION_CATALOGUE_IMAGE }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: {{ required "Missing value PUBLISHERS_API_MEMORY" .Values.PUBLISHERS_API_MEMORY | quote }}
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
      restartPolicy: Always
status: {}
