apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    fdk.service: publishers-api
  name: publishers-api
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    fdk.service: publishers-api
status:
  loadBalancer: {}
